import Head from "next/head"
import Link from "next/link"

import { PropsWithChildren } from "react"
import { IconProps } from "./pages/[icon]"
import { RouteTransition } from "./route-transition"

export function SharedApp({ name, data, children }: PropsWithChildren<IconProps>) {
	return (
		<>
			{/* Meta */}
			<Head>
				<title>{name}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* App */}
			<div className="p-16">
				<nav className="flex flex-wrap gap-10">
					<Link className="h-32 px-16 flex items-center bg-[orange]" href="/">
						<div>Home</div>
					</Link>
					<Link className="h-32 px-16 flex items-center bg-[orange]" href="/foo">
						<div>foo</div>
					</Link>
					<Link className="h-32 px-16 flex items-center bg-[orange]" href="/foo-bar">
						<div>foo bar</div>
					</Link>
					<Link className="h-32 px-16 flex items-center bg-[orange]" href="/foo-bar-baz">
						<div>foo bar baz</div>
					</Link>
				</nav>
				<main>
					<RouteTransition>{children}</RouteTransition>
					<RouteTransition>Hello world!</RouteTransition>
				</main>
			</div>
		</>
	)
}
